### ISSUE TITLE
天地图下载100%失败

### ISSUE THREAD

**Issue by yeastone** [FreeGIS/map-tile-downloader#1]
切片下载失败率高达百分百。。有人遇到吗

**Comment by FreeGIS** [comment]
> 切片下载失败率高达百分百。。有人遇到吗

天地图的验证非常严了，目前已经不能用了，经常封ip。

**Comment by FreeGIS** [comment]
> 切片下载失败率高达百分百。。有人遇到吗

使用企业应用token
