### ISSUE TITLE
请教一个与该项目不太相关的问题，请问得到了xyz的格式切片，最终应该用什么形式让服务器发布

### ISSUE THREAD

**Issue by fredsun** [FreeGIS/map-tile-downloader#2]
是直接暴露服务器的文件目录地址进行读取吗，还是可以发布成什么wmts之类的服务，感觉非arcgis的这种纯xyz的切片似乎不太适合发布成服务？

**Comment by FreeGIS** [comment]
直接nginx发布，iis tomcat jetty都可以
